
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_code_along_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: rails_code_along_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: rails_code_along_production
  username: rails_code_along
  password: <%= ENV["RAILS_CODE_ALONG_DATABASE_PASSWORD"] %>
